-- Create the table if it doesn't exist
CREATE TABLE IF NOT EXISTS degree_courses(
    id INT AUTO_INCREMENT PRIMARY KEY,
    course_id IN,
    degree_id BIGINT UNSIGNED,
    degree_name VARCHAR(255),
    similarity_score FLOAT DEFAULT 1.0,
    INDEX (course_id),
    INDEX (degree_id),
    FOREIGN KEY (course_id) REFERENCES courses(id),
    FOREIGN KEY (degree_id) REFERENCES degrees(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Ensure courses exist in reference table

-- Insert degree-course mappings
INSERT INTO degree_courses
(course_id, category, area_name, degree_id, degree_name, similarity_score)
VALUES
(2230, 'Mathematics & Statistics', 'Mathematics & Statistics', 513, 'Agronomie', 1.0),
(2555, 'Mathematics & Statistics', 'Mathematics & Statistics', 513, 'Agronomie', 1.0),
(2556, 'Mathematics & Statistics', 'Mathematics & Statistics', 513, 'Agronomie', 1.0),
(1137, 'Mathematics & Statistics', 'Mathematics & Statistics', 513, 'Agronomie', 1.0),
(2613, 'Mathematics & Statistics', 'Mathematics & Statistics', 513, 'Agronomie', 1.0),
(2547, 'Life Sciences', 'Life Sciences', 484, 'Production végétale', 1.0),
(2474, 'Life Sciences', 'Life Sciences', 484, 'Production végétale', 1.0),
(2244, 'Life Sciences', 'Life Sciences', 484, 'Production végétale', 1.0),
(2241, 'Life Sciences', 'Life Sciences', 484, 'Production végétale', 1.0),
(2474, 'Mathematics & Statistics', 'Mathematics & Statistics', 512, 'Sciences végétales', 1.0),
(2232, 'Mathematics & Statistics', 'Mathematics & Statistics', 512, 'Sciences végétales', 1.0),
(2176, 'Mathematics & Statistics', 'Mathematics & Statistics', 512, 'Sciences végétales', 1.0),
(2002, 'Mathematics & Statistics', 'Mathematics & Statistics', 512, 'Sciences végétales', 1.0),
(2238, 'Mathematics & Statistics', 'Mathematics & Statistics', 514, 'Horticulture', 1.0),
(2258, 'Mathematics & Statistics', 'Mathematics & Statistics', 514, 'Horticulture', 1.0),
(2260, 'Mathematics & Statistics', 'Mathematics & Statistics', 514, 'Horticulture', 1.0),
(2257, 'Mathematics & Statistics', 'Mathematics & Statistics', 514, 'Horticulture', 1.0),
(2253, 'Life Sciences', 'Life Sciences', 494, 'Gestion d''entreprise horticole', 1.0),
(2255, 'Life Sciences', 'Life Sciences', 494, 'Gestion d''entreprise horticole', 1.0),
(2259, 'Life Sciences', 'Life Sciences', 499, 'Gestion du gazon', 1.0),
(2255, 'Life Sciences', 'Life Sciences', 499, 'Gestion du gazon', 1.0),
(2246, 'Life Sciences', 'Life Sciences', 499, 'Gestion du gazon', 1.0),
(2538, 'Engineering', 'Engineering', 230, 'Génie agricole', 1.0),
(2245, 'Engineering', 'Engineering', 230, 'Génie agricole', 1.0),
(2031, 'Engineering', 'Engineering', 230, 'Génie agricole', 1.0),
(2547, 'Life Sciences', 'Life Sciences', 480, 'Mécanique agricole', 1.0),
(2256, 'Life Sciences', 'Life Sciences', 483, 'Aquaculture', 1.0),
(2368, 'Life Sciences', 'Life Sciences', 483, 'Aquaculture', 1.0),
(2028, 'Life Sciences', 'Life Sciences', 483, 'Aquaculture', 1.0),
(2158, 'Life Sciences', 'Life Sciences', 483, 'Aquaculture', 1.0),
(2235, 'Life Sciences', 'Life Sciences', 483, 'Aquaculture', 1.0),
(1173, 'Life Sciences', 'Life Sciences', 483, 'Aquaculture', 1.0),
(2612, 'Life Sciences', 'Life Sciences', 486, 'Science équine', 1.0),
(2612, 'Life Sciences', 'Life Sciences', 487, 'Sciences animales', 1.0),
(2536, 'Life Sciences', 'Life Sciences', 487, 'Sciences animales', 1.0),
(2243, 'Life Sciences', 'Life Sciences', 487, 'Sciences animales', 1.0),
(2244, 'Mathematics & Statistics', 'Mathematics & Statistics', 508, 'Science laitière', 1.0),
(2557, 'Life Sciences', 'Life Sciences', 473, 'Agroalimentaire', 1.0),
(2547, 'Life Sciences', 'Life Sciences', 473, 'Agroalimentaire', 1.0),
(2474, 'Life Sciences', 'Life Sciences', 473, 'Agroalimentaire', 1.0),
(2538, 'Life Sciences', 'Life Sciences', 473, 'Agroalimentaire', 1.0),
(2072, 'Life Sciences', 'Life Sciences', 473, 'Agroalimentaire', 1.0),
(2027, 'Life Sciences', 'Life Sciences', 473, 'Agroalimentaire', 1.0),
(2233, 'Life Sciences', 'Life Sciences', 473, 'Agroalimentaire', 1.0),
(2072, 'Agriculture Economics', 'Agriculture and Natural Resources', 3, 'Économie agricole', 1.0),
(2242, 'Agriculture Economics', 'Agriculture and Natural Resources', 3, 'Économie agricole', 1.0),
(2248, 'Agriculture Economics', 'Agriculture and Natural Resources', 3, 'Économie agricole', 1.0),
(2252, 'Agriculture Economics', 'Agriculture and Natural Resources', 9, 'Sylviculture', 1.0),
(2249, 'Agriculture Economics', 'Agriculture and Natural Resources', 9, 'Sylviculture', 1.0),
(2232, 'Agriculture Economics', 'Agriculture and Natural Resources', 9, 'Sylviculture', 1.0),
(2239, 'Agriculture Economics', 'Agriculture and Natural Resources', 9, 'Sylviculture', 1.0),
(2259, 'Agriculture Economics', 'Agriculture and Natural Resources', 9, 'Sylviculture', 1.0),
(2247, 'Agriculture Economics', 'Agriculture and Natural Resources', 9, 'Sylviculture', 1.0),
(2246, 'Agriculture Economics', 'Agriculture and Natural Resources', 9, 'Sylviculture', 1.0),
(2262, 'Agriculture Economics', 'Agriculture and Natural Resources', 9, 'Sylviculture', 1.0),
(2263, 'Agriculture Economics', 'Agriculture and Natural Resources', 9, 'Sylviculture', 1.0),
(2612, 'Agriculture Economics', 'Agriculture and Natural Resources', 9, 'Sylviculture', 1.0),
(2536, 'Agriculture Economics', 'Agriculture and Natural Resources', 9, 'Sylviculture', 1.0),
(2243, 'Agriculture Economics', 'Agriculture and Natural Resources', 9, 'Sylviculture', 1.0),
(2042, 'Arts & Design', 'Arts & Design', 19, 'Sciences de l''environnement', 1.0),
(1985, 'Arts & Design', 'Arts & Design', 19, 'Sciences de l''environnement', 1.0),
(1385, 'Arts & Design', 'Arts & Design', 19, 'Sciences de l''environnement', 1.0),
(1988, 'Arts & Design', 'Arts & Design', 19, 'Sciences de l''environnement', 1.0),
(2247, 'Mathematics & Statistics', 'Mathematics & Statistics', 520, 'Conservation des ressources naturelles', 1.0),
(2248, 'Mathematics & Statistics', 'Mathematics & Statistics', 520, 'Conservation des ressources naturelles', 1.0),
(1113, 'Mathematics & Statistics', 'Mathematics & Statistics', 520, 'Conservation des ressources naturelles', 1.0),
(1130, 'Mathematics & Statistics', 'Mathematics & Statistics', 520, 'Conservation des ressources naturelles', 1.0),
(1162, 'Mathematics & Statistics', 'Mathematics & Statistics', 520, 'Conservation des ressources naturelles', 1.0),
(1137, 'Mathematics & Statistics', 'Mathematics & Statistics', 521, 'Études environnementales', 1.0),
(2031, 'Mathematics & Statistics', 'Mathematics & Statistics', 521, 'Études environnementales', 1.0),
(2315, 'Mathematics & Statistics', 'Mathematics & Statistics', 521, 'Études environnementales', 1.0),
(1987, 'Mathematics & Statistics', 'Mathematics & Statistics', 521, 'Études environnementales', 1.0),
(2340, 'Mathematics & Statistics', 'Mathematics & Statistics', 524, 'Planification environnementale', 1.0),
(2058, 'Mathematics & Statistics', 'Mathematics & Statistics', 524, 'Planification environnementale', 1.0),
(1144, 'Mathematics & Statistics', 'Mathematics & Statistics', 524, 'Planification environnementale', 1.0),
(1975, 'Mathematics & Statistics', 'Mathematics & Statistics', 524, 'Planification environnementale', 1.0),
(2544, 'Environmental Sciences', 'Environmental Sciences', 323, 'Conception environnementale', 1.0),
(2564, 'Environmental Sciences', 'Environmental Sciences', 323, 'Conception environnementale', 1.0),
(2537, 'Environmental Sciences', 'Environmental Sciences', 323, 'Conception environnementale', 1.0),
(1369, 'Environmental Sciences', 'Environmental Sciences', 323, 'Conception environnementale', 1.0),
(2593, 'Environmental Sciences', 'Environmental Sciences', 323, 'Conception environnementale', 1.0),
(2071, 'Environmental Sciences', 'Environmental Sciences', 323, 'Conception environnementale', 1.0),
(1173, 'Mathematics & Statistics', 'Mathematics & Statistics', 527, 'Sciences et gestion de la pêche', 1.0),
(2032, 'Mathematics & Statistics', 'Mathematics & Statistics', 527, 'Sciences et gestion de la pêche', 1.0),
(2067, 'Mathematics & Statistics', 'Mathematics & Statistics', 527, 'Sciences et gestion de la pêche', 1.0),
(2246, 'Mathematics & Statistics', 'Mathematics & Statistics', 528, 'Sciences forestières et biologie', 1.0),
(2184, 'Mathematics & Statistics', 'Mathematics & Statistics', 528, 'Sciences forestières et biologie', 1.0),
(2002, 'Mathematics & Statistics', 'Mathematics & Statistics', 528, 'Sciences forestières et biologie', 1.0),
(2176, 'Mathematics & Statistics', 'Mathematics & Statistics', 534, 'Science et gestion de la faune', 1.0),
(2007, 'Mathematics & Statistics', 'Mathematics & Statistics', 534, 'Science et gestion de la faune', 1.0),
(1166, 'Other', 'Other', 738, 'Gestion du traitement des eaux usées', 1.0),
(2548, 'Other', 'Other', 738, 'Gestion du traitement des eaux usées', 1.0),
(1993, 'Other', 'Other', 738, 'Gestion du traitement des eaux usées', 1.0),
(1976, 'Other', 'Other', 738, 'Gestion du traitement des eaux usées', 1.0),
(1860, 'Other', 'Other', 738, 'Gestion du traitement des eaux usées', 1.0),
(1738, 'Other', 'Other', 738, 'Gestion du traitement des eaux usées', 1.0),
(1687, 'Other', 'Other', 738, 'Gestion du traitement des eaux usées', 1.0),
(1611, 'Other', 'Other', 738, 'Gestion du traitement des eaux usées', 1.0),
(1541, 'Other', 'Other', 738, 'Gestion du traitement des eaux usées', 1.0),
(2601, 'Other', 'Other', 740, 'Gestion des matières dangereuses', 1.0),
(2563, 'Other', 'Other', 740, 'Gestion des matières dangereuses', 1.0),
(1172, 'Arts & Design', 'Arts & Design', 20, 'Biologie', 1.0),
(1164, 'Arts & Design', 'Arts & Design', 20, 'Biologie', 1.0),
(2184, 'Arts & Design', 'Arts & Design', 20, 'Biologie', 1.0),
(2002, 'Arts & Design', 'Arts & Design', 20, 'Biologie', 1.0),
(1118, 'Arts & Design', 'Arts & Design', 22, 'Botanique', 1.0),
(2565, 'Arts & Design', 'Arts & Design', 22, 'Botanique', 1.0),
(2176, 'Arts & Design', 'Arts & Design', 22, 'Botanique', 1.0),
(2041, 'Arts & Design', 'Arts & Design', 23, 'Biologie moléculaire', 1.0),
(1165, 'Arts & Design', 'Arts & Design', 24, 'Écologie', 1.0),
(2247, 'Arts & Design', 'Arts & Design', 24, 'Écologie', 1.0),
(2553, 'Arts & Design', 'Arts & Design', 25, 'Génétique', 1.0),
(1384, 'Arts & Design', 'Arts & Design', 26, 'Microbiologie', 1.0),
(1159, 'Arts & Design', 'Arts & Design', 27, 'Pharmacologie', 1.0),
(1852, 'Engineering', 'Engineering', 260, 'Bioinformatique', 1.0),
(1730, 'Engineering', 'Engineering', 260, 'Bioinformatique', 1.0),
(1679, 'Engineering', 'Engineering', 260, 'Bioinformatique', 1.0),
(1603, 'Engineering', 'Engineering', 260, 'Bioinformatique', 1.0),
(2294, 'Engineering', 'Engineering', 260, 'Bioinformatique', 1.0),
(1114, 'Engineering', 'Engineering', 261, 'Sciences biomédicales', 1.0),
(1365, 'Engineering', 'Engineering', 261, 'Sciences biomédicales', 1.0),
(2048, 'Engineering', 'Engineering', 262, 'Biotechnologie', 1.0),
(2159, 'Engineering', 'Engineering', 262, 'Biotechnologie', 1.0),
(1984, 'Engineering', 'Engineering', 262, 'Biotechnologie', 1.0),
(1143, 'Engineering', 'Engineering', 262, 'Biotechnologie', 1.0),
(1985, 'Engineering', 'Engineering', 262, 'Biotechnologie', 1.0),
(1999, 'Environmental Sciences', 'Environmental Sciences', 384, 'Biologie Marine', 1.0),
(1173, 'Environmental Sciences', 'Environmental Sciences', 384, 'Biologie Marine', 1.0),
(2032, 'Environmental Sciences', 'Environmental Sciences', 384, 'Biologie Marine', 1.0),
(1176, 'Other', 'Other', 918, 'Pathologie', 1.0),
(2294, 'Other', 'Other', 929, 'Biologie computationnelle', 1.0),
(1119, 'Computer Science & IT', 'Computer Science & IT', 53, 'L''informatique', 1.0),
(1155, 'Computer Science & IT', 'Computer Science & IT', 53, 'L''informatique', 1.0),
(1433, 'Computer Science & IT', 'Computer Science & IT', 53, 'L''informatique', 1.0),
(1524, 'Computer Science & IT', 'Computer Science & IT', 53, 'L''informatique', 1.0),
(1537, 'Computer Science & IT', 'Computer Science & IT', 53, 'L''informatique', 1.0),
(2611, 'Computer Science & IT', 'Computer Science & IT', 53, 'L''informatique', 1.0),
(2602, 'Computer Science & IT', 'Computer Science & IT', 53, 'L''informatique', 1.0),
(1147, 'Engineering', 'Engineering', 299, 'Cybersécurité', 1.0),
(1467, 'Engineering', 'Engineering', 299, 'Cybersécurité', 1.0),
(1531, 'Engineering', 'Engineering', 299, 'Cybersécurité', 1.0),
(2329, 'Engineering', 'Engineering', 299, 'Cybersécurité', 1.0),
(2302, 'Engineering', 'Engineering', 299, 'Cybersécurité', 1.0),
(2192, 'Engineering', 'Engineering', 299, 'Cybersécurité', 1.0),
(2055, 'Engineering', 'Engineering', 299, 'Cybersécurité', 1.0),
(1136, 'Environmental Sciences', 'Environmental Sciences', 301, 'Science des données', 1.0),
(1181, 'Environmental Sciences', 'Environmental Sciences', 301, 'Science des données', 1.0),
(1408, 'Environmental Sciences', 'Environmental Sciences', 301, 'Science des données', 1.0),
(1543, 'Environmental Sciences', 'Environmental Sciences', 301, 'Science des données', 1.0),
(2336, 'Environmental Sciences', 'Environmental Sciences', 301, 'Science des données', 1.0),
(2335, 'Environmental Sciences', 'Environmental Sciences', 301, 'Science des données', 1.0),
(2296, 'Environmental Sciences', 'Environmental Sciences', 301, 'Science des données', 1.0),
(2288, 'Environmental Sciences', 'Environmental Sciences', 301, 'Science des données', 1.0),
(2193, 'Environmental Sciences', 'Environmental Sciences', 301, 'Science des données', 1.0),
(2303, 'Environmental Sciences', 'Environmental Sciences', 302, 'Gestion de base de données', 1.0),
(2300, 'Environmental Sciences', 'Environmental Sciences', 302, 'Gestion de base de données', 1.0),
(2301, 'Environmental Sciences', 'Environmental Sciences', 302, 'Gestion de base de données', 1.0),
(1405, 'Other', 'Other', 602, 'Intelligence artificielle', 1.0),
(1475, 'Other', 'Other', 602, 'Intelligence artificielle', 1.0),
(2589, 'Other', 'Other', 602, 'Intelligence artificielle', 1.0),
(2561, 'Other', 'Other', 602, 'Intelligence artificielle', 1.0),
(2289, 'Other', 'Other', 602, 'Intelligence artificielle', 1.0),
(2188, 'Other', 'Other', 602, 'Intelligence artificielle', 1.0),
(1972, 'Other', 'Other', 602, 'Intelligence artificielle', 1.0),
(1375, 'Other', 'Other', 603, 'Informatique', 1.0),
(1380, 'Other', 'Other', 603, 'Informatique', 1.0),
(1396, 'Other', 'Other', 603, 'Informatique', 1.0),
(1469, 'Other', 'Other', 603, 'Informatique', 1.0),
(1471, 'Other', 'Other', 604, 'Informatique', 1.0),
(1528, 'Other', 'Other', 604, 'Informatique', 1.0),
(1544, 'Other', 'Other', 604, 'Informatique', 1.0),
(2551, 'Other', 'Other', 604, 'Informatique', 1.0),
(2470, 'Other', 'Other', 604, 'Informatique', 1.0),
(1516, 'Other', 'Other', 611, 'Conception de sites Web', 1.0),
(1835, 'Other', 'Other', 611, 'Conception de sites Web', 1.0),
(1896, 'Other', 'Other', 611, 'Conception de sites Web', 1.0),
(1970, 'Other', 'Other', 611, 'Conception de sites Web', 1.0),
(2309, 'Other', 'Other', 612, 'Infographie', 1.0),
(2070, 'Other', 'Other', 612, 'Infographie', 1.0),
(2163, 'Other', 'Other', 613, 'Programmation de simulations', 1.0),
(2156, 'Other', 'Other', 613, 'Programmation de simulations', 1.0),
(2060, 'Other', 'Other', 613, 'Programmation de simulations', 1.0),
(1126, 'Other', 'Other', 615, 'Administration des systèmes réseau', 1.0),
(1150, 'Other', 'Other', 615, 'Administration des systèmes réseau', 1.0),
(1434, 'Other', 'Other', 615, 'Administration des systèmes réseau', 1.0),
(1893, 'Other', 'Other', 615, 'Administration des systèmes réseau', 1.0),
(1892, 'Other', 'Other', 616, 'Gestion du réseau', 1.0),
(2190, 'Other', 'Other', 616, 'Gestion du réseau', 1.0),
(2465, 'Other', 'Other', 616, 'Gestion du réseau', 1.0),
(2586, 'Other', 'Other', 616, 'Gestion du réseau', 1.0),
(1899, 'Other', 'Other', 619, 'Gestion des technologies de l''information', 1.0),
(1777, 'Other', 'Other', 619, 'Gestion des technologies de l''information', 1.0),
(1676, 'Other', 'Other', 619, 'Gestion des technologies de l''information', 1.0),
(1600, 'Other', 'Other', 619, 'Gestion des technologies de l''information', 1.0),
(1121, 'Computer Science & IT', 'Computer Science & IT', 57, 'Mathématiques', 1.0),
(1133, 'Computer Science & IT', 'Computer Science & IT', 57, 'Mathématiques', 1.0),
(1148, 'Computer Science & IT', 'Computer Science & IT', 57, 'Mathématiques', 1.0),
(1175, 'Computer Science & IT', 'Computer Science & IT', 57, 'Mathématiques', 1.0),
(2004, 'Computer Science & IT', 'Computer Science & IT', 57, 'Mathématiques', 1.0),
(2050, 'Computer Science & IT', 'Computer Science & IT', 57, 'Mathématiques', 1.0),
(2182, 'Computer Science & IT', 'Computer Science & IT', 57, 'Mathématiques', 1.0),
(1371, 'Computer Science & IT', 'Computer Science & IT', 58, 'Mathématiques appliquées', 1.0),
(1376, 'Computer Science & IT', 'Computer Science & IT', 58, 'Mathématiques appliquées', 1.0),
(1399, 'Computer Science & IT', 'Computer Science & IT', 58, 'Mathématiques appliquées', 1.0),
(2056, 'Computer Science & IT', 'Computer Science & IT', 58, 'Mathématiques appliquées', 1.0),
(2178, 'Computer Science & IT', 'Computer Science & IT', 58, 'Mathématiques appliquées', 1.0),
(2166, 'Computer Science & IT', 'Computer Science & IT', 58, 'Mathématiques appliquées', 1.0),
(1120, 'Computer Science & IT', 'Computer Science & IT', 59, 'Statistiques', 1.0),
(1157, 'Computer Science & IT', 'Computer Science & IT', 59, 'Statistiques', 1.0),
(1169, 'Computer Science & IT', 'Computer Science & IT', 59, 'Statistiques', 1.0),
(1983, 'Computer Science & IT', 'Computer Science & IT', 59, 'Statistiques', 1.0),
(2049, 'Computer Science & IT', 'Computer Science & IT', 59, 'Statistiques', 1.0),
(2037, 'Computer Science & IT', 'Computer Science & IT', 59, 'Statistiques', 1.0),
(2022, 'Computer Science & IT', 'Computer Science & IT', 59, 'Statistiques', 1.0),
(1152, 'Other', 'Other', 718, 'Recherche opérationnelle', 1.0),
(2338, 'Other', 'Other', 718, 'Recherche opérationnelle', 1.0),
(2164, 'Other', 'Other', 718, 'Recherche opérationnelle', 1.0),
(1409, 'Other', 'Other', 946, 'Mathématiques computationnelles', 1.0),
(2026, 'Other', 'Other', 946, 'Mathématiques computationnelles', 1.0),
(2340, 'Computer Science & IT', 'Computer Science & IT', 77, 'Architecture', 1.0),
(2436, 'Computer Science & IT', 'Computer Science & IT', 77, 'Architecture', 1.0),
(2437, 'Computer Science & IT', 'Computer Science & IT', 77, 'Architecture', 1.0),
(2438, 'Computer Science & IT', 'Computer Science & IT', 77, 'Architecture', 1.0),
(2439, 'Computer Science & IT', 'Computer Science & IT', 77, 'Architecture', 1.0),
(2440, 'Computer Science & IT', 'Computer Science & IT', 77, 'Architecture', 1.0),
(2441, 'Computer Science & IT', 'Computer Science & IT', 77, 'Architecture', 1.0),
(2442, 'Computer Science & IT', 'Computer Science & IT', 77, 'Architecture', 1.0),
(2339, 'Computer Science & IT', 'Computer Science & IT', 84, 'Génie civil', 1.0),
(2594, 'Computer Science & IT', 'Computer Science & IT', 84, 'Génie civil', 1.0),
(2552, 'Computer Science & IT', 'Computer Science & IT', 84, 'Génie civil', 1.0),
(2444, 'Computer Science & IT', 'Computer Science & IT', 84, 'Génie civil', 1.0),
(2445, 'Computer Science & IT', 'Computer Science & IT', 84, 'Génie civil', 1.0),
(2446, 'Computer Science & IT', 'Computer Science & IT', 84, 'Génie civil', 1.0),
(2447, 'Computer Science & IT', 'Computer Science & IT', 84, 'Génie civil', 1.0),
(2448, 'Computer Science & IT', 'Computer Science & IT', 84, 'Génie civil', 1.0),
(2449, 'Computer Science & IT', 'Computer Science & IT', 84, 'Génie civil', 1.0),
(2450, 'Computer Science & IT', 'Computer Science & IT', 84, 'Génie civil', 1.0),
(2451, 'Computer Science & IT', 'Computer Science & IT', 84, 'Génie civil', 1.0),
(2452, 'Computer Science & IT', 'Computer Science & IT', 84, 'Génie civil', 1.0),
(2455, 'Computer Science & IT', 'Computer Science & IT', 84, 'Génie civil', 1.0),
(2456, 'Computer Science & IT', 'Computer Science & IT', 84, 'Génie civil', 1.0),
(2344, 'Computer Science & IT', 'Computer Science & IT', 84, 'Génie civil', 1.0),
(2345, 'Computer Science & IT', 'Computer Science & IT', 84, 'Génie civil', 1.0),
(2320, 'Computer Science & IT', 'Computer Science & IT', 84, 'Génie civil', 1.0),
(2306, 'Computer Science & IT', 'Computer Science & IT', 84, 'Génie civil', 1.0),
(2043, 'Computer Science & IT', 'Computer Science & IT', 84, 'Génie civil', 1.0),
(2017, 'Computer Science & IT', 'Computer Science & IT', 84, 'Génie civil', 1.0),
(2010, 'Computer Science & IT', 'Computer Science & IT', 84, 'Génie civil', 1.0),
(1864, 'Computer Science & IT', 'Computer Science & IT', 84, 'Génie civil', 1.0),
(1787, 'Computer Science & IT', 'Computer Science & IT', 84, 'Génie civil', 1.0),
(1742, 'Computer Science & IT', 'Computer Science & IT', 84, 'Génie civil', 1.0),
(1691, 'Computer Science & IT', 'Computer Science & IT', 84, 'Génie civil', 1.0),
(1615, 'Computer Science & IT', 'Computer Science & IT', 84, 'Génie civil', 1.0),
(1545, 'Computer Science & IT', 'Computer Science & IT', 84, 'Génie civil', 1.0),
(2052, 'Computer Science & IT', 'Computer Science & IT', 84, 'Génie civil', 1.0),
(2034, 'Computer Science & IT', 'Computer Science & IT', 84, 'Génie civil', 1.0),
(1909, 'Computer Science & IT', 'Computer Science & IT', 84, 'Génie civil', 1.0),
(2231, 'Computer Science & IT', 'Computer Science & IT', 84, 'Génie civil', 1.0),
(2013, 'Computer Science & IT', 'Computer Science & IT', 84, 'Génie civil', 1.0),
(2014, 'Computer Science & IT', 'Computer Science & IT', 84, 'Génie civil', 1.0),
(2018, 'Computer Science & IT', 'Computer Science & IT', 84, 'Génie civil', 1.0),
(2019, 'Computer Science & IT', 'Computer Science & IT', 84, 'Génie civil', 1.0),
(2236, 'Computer Science & IT', 'Computer Science & IT', 84, 'Génie civil', 1.0),
(2240, 'Computer Science & IT', 'Computer Science & IT', 84, 'Génie civil', 1.0),
(2454, 'Computer Science & IT', 'Computer Science & IT', 84, 'Génie civil', 1.0),
(2457, 'Computer Science & IT', 'Computer Science & IT', 84, 'Génie civil', 1.0),
(2453, 'Computer Science & IT', 'Computer Science & IT', 84, 'Génie civil', 1.0),
(1139, 'Computer Science & IT', 'Computer Science & IT', 83, 'Génie Chimique', 1.0),
(1130, 'Computer Science & IT', 'Computer Science & IT', 83, 'Génie Chimique', 1.0),
(1115, 'Computer Science & IT', 'Computer Science & IT', 83, 'Génie Chimique', 1.0),
(1117, 'Computer Science & IT', 'Computer Science & IT', 83, 'Génie Chimique', 1.0),
(1131, 'Computer Science & IT', 'Computer Science & IT', 83, 'Génie Chimique', 1.0),
(1138, 'Computer Science & IT', 'Computer Science & IT', 83, 'Génie Chimique', 1.0),
(1145, 'Computer Science & IT', 'Computer Science & IT', 83, 'Génie Chimique', 1.0),
(1154, 'Computer Science & IT', 'Computer Science & IT', 83, 'Génie Chimique', 1.0),
(1160, 'Computer Science & IT', 'Computer Science & IT', 83, 'Génie Chimique', 1.0),
(1168, 'Computer Science & IT', 'Computer Science & IT', 83, 'Génie Chimique', 1.0),
(1367, 'Computer Science & IT', 'Computer Science & IT', 83, 'Génie Chimique', 1.0),
(1368, 'Computer Science & IT', 'Computer Science & IT', 83, 'Génie Chimique', 1.0),
(1379, 'Computer Science & IT', 'Computer Science & IT', 83, 'Génie Chimique', 1.0),
(1382, 'Computer Science & IT', 'Computer Science & IT', 83, 'Génie Chimique', 1.0),
(1383, 'Computer Science & IT', 'Computer Science & IT', 83, 'Génie Chimique', 1.0),
(1394, 'Computer Science & IT', 'Computer Science & IT', 83, 'Génie Chimique', 1.0),
(1431, 'Computer Science & IT', 'Computer Science & IT', 83, 'Génie Chimique', 1.0),
(1438, 'Computer Science & IT', 'Computer Science & IT', 83, 'Génie Chimique', 1.0),
(2473, 'Computer Science & IT', 'Computer Science & IT', 83, 'Génie Chimique', 1.0),
(2312, 'Computer Science & IT', 'Computer Science & IT', 83, 'Génie Chimique', 1.0),
(2047, 'Computer Science & IT', 'Computer Science & IT', 83, 'Génie Chimique', 1.0),
(1978, 'Computer Science & IT', 'Computer Science & IT', 83, 'Génie Chimique', 1.0),
(2554, 'Computer Science & IT', 'Computer Science & IT', 83, 'Génie Chimique', 1.0),
(2273, 'Computer Science & IT', 'Computer Science & IT', 83, 'Génie Chimique', 1.0),
(2068, 'Computer Science & IT', 'Computer Science & IT', 83, 'Génie Chimique', 1.0),
(2057, 'Computer Science & IT', 'Computer Science & IT', 83, 'Génie Chimique', 1.0),
(2005, 'Computer Science & IT', 'Computer Science & IT', 83, 'Génie Chimique', 1.0),
(1998, 'Computer Science & IT', 'Computer Science & IT', 83, 'Génie Chimique', 1.0),
(1977, 'Computer Science & IT', 'Computer Science & IT', 83, 'Génie Chimique', 1.0),
(2044, 'Computer Science & IT', 'Computer Science & IT', 83, 'Génie Chimique', 1.0),
(1161, 'Computer Science & IT', 'Computer Science & IT', 86, 'Génie électrique', 1.0),
(1372, 'Computer Science & IT', 'Computer Science & IT', 86, 'Génie électrique', 1.0),
(1378, 'Computer Science & IT', 'Computer Science & IT', 86, 'Génie électrique', 1.0),
(1389, 'Computer Science & IT', 'Computer Science & IT', 86, 'Génie électrique', 1.0),
(1390, 'Computer Science & IT', 'Computer Science & IT', 86, 'Génie électrique', 1.0),
(1397, 'Computer Science & IT', 'Computer Science & IT', 86, 'Génie électrique', 1.0),
(1402, 'Computer Science & IT', 'Computer Science & IT', 86, 'Génie électrique', 1.0),
(1432, 'Computer Science & IT', 'Computer Science & IT', 86, 'Génie électrique', 1.0),
(1466, 'Computer Science & IT', 'Computer Science & IT', 86, 'Génie électrique', 1.0),
(1472, 'Computer Science & IT', 'Computer Science & IT', 86, 'Génie électrique', 1.0),
(1473, 'Computer Science & IT', 'Computer Science & IT', 86, 'Génie électrique', 1.0),
(1476, 'Computer Science & IT', 'Computer Science & IT', 86, 'Génie électrique', 1.0),
(2604, 'Computer Science & IT', 'Computer Science & IT', 86, 'Génie électrique', 1.0),
(2346, 'Computer Science & IT', 'Computer Science & IT', 86, 'Génie électrique', 1.0),
(2347, 'Computer Science & IT', 'Computer Science & IT', 86, 'Génie électrique', 1.0),
(2314, 'Computer Science & IT', 'Computer Science & IT', 86, 'Génie électrique', 1.0),
(2054, 'Computer Science & IT', 'Computer Science & IT', 86, 'Génie électrique', 1.0),
(2035, 'Computer Science & IT', 'Computer Science & IT', 86, 'Génie électrique', 1.0),
(2472, 'Computer Science & IT', 'Computer Science & IT', 86, 'Génie électrique', 1.0),
(2532, 'Computer Science & IT', 'Computer Science & IT', 86, 'Génie électrique', 1.0),
(1180, 'Computer Science & IT', 'Computer Science & IT', 90, 'Génie Industriel', 1.0),
(1381, 'Computer Science & IT', 'Computer Science & IT', 90, 'Génie Industriel', 1.0),
(1392, 'Computer Science & IT', 'Computer Science & IT', 90, 'Génie Industriel', 1.0),
(1395, 'Computer Science & IT', 'Computer Science & IT', 90, 'Génie Industriel', 1.0),
(1401, 'Computer Science & IT', 'Computer Science & IT', 90, 'Génie Industriel', 1.0),
(1407, 'Computer Science & IT', 'Computer Science & IT', 90, 'Génie Industriel', 1.0),
(1435, 'Computer Science & IT', 'Computer Science & IT', 90, 'Génie Industriel', 1.0),
(1468, 'Computer Science & IT', 'Computer Science & IT', 90, 'Génie Industriel', 1.0),
(1517, 'Computer Science & IT', 'Computer Science & IT', 90, 'Génie Industriel', 1.0),
(1518, 'Computer Science & IT', 'Computer Science & IT', 90, 'Génie Industriel', 1.0),
(1519, 'Computer Science & IT', 'Computer Science & IT', 90, 'Génie Industriel', 1.0),
(1520, 'Computer Science & IT', 'Computer Science & IT', 90, 'Génie Industriel', 1.0),
(1521, 'Computer Science & IT', 'Computer Science & IT', 90, 'Génie Industriel', 1.0),
(2197, 'Computer Science & IT', 'Computer Science & IT', 90, 'Génie Industriel', 1.0),
(2199, 'Computer Science & IT', 'Computer Science & IT', 90, 'Génie Industriel', 1.0),
(2201, 'Computer Science & IT', 'Computer Science & IT', 90, 'Génie Industriel', 1.0),
(2603, 'Computer Science & IT', 'Computer Science & IT', 90, 'Génie Industriel', 1.0),
(2592, 'Computer Science & IT', 'Computer Science & IT', 90, 'Génie Industriel', 1.0),
(2324, 'Computer Science & IT', 'Computer Science & IT', 90, 'Génie Industriel', 1.0),
(2053, 'Computer Science & IT', 'Computer Science & IT', 90, 'Génie Industriel', 1.0),
(2033, 'Computer Science & IT', 'Computer Science & IT', 90, 'Génie Industriel', 1.0),
(2315, 'Computer Science & IT', 'Computer Science & IT', 90, 'Génie Industriel', 1.0),
(1374, 'Computer Science & IT', 'Computer Science & IT', 92, 'Génie mécanique', 1.0),
(1391, 'Computer Science & IT', 'Computer Science & IT', 92, 'Génie mécanique', 1.0),
(1393, 'Computer Science & IT', 'Computer Science & IT', 92, 'Génie mécanique', 1.0),
(1400, 'Computer Science & IT', 'Computer Science & IT', 92, 'Génie mécanique', 1.0),
(1406, 'Computer Science & IT', 'Computer Science & IT', 92, 'Génie mécanique', 1.0),
(1410, 'Computer Science & IT', 'Computer Science & IT', 92, 'Génie mécanique', 1.0),
(1430, 'Computer Science & IT', 'Computer Science & IT', 92, 'Génie mécanique', 1.0),
(1470, 'Computer Science & IT', 'Computer Science & IT', 92, 'Génie mécanique', 1.0),
(2313, 'Computer Science & IT', 'Computer Science & IT', 92, 'Génie mécanique', 1.0),
(2198, 'Computer Science & IT', 'Computer Science & IT', 92, 'Génie mécanique', 1.0),
(2194, 'Computer Science & IT', 'Computer Science & IT', 92, 'Génie mécanique', 1.0),
(1861, 'Computer Science & IT', 'Computer Science & IT', 92, 'Génie mécanique', 1.0),
(1739, 'Computer Science & IT', 'Computer Science & IT', 92, 'Génie mécanique', 1.0),
(1688, 'Computer Science & IT', 'Computer Science & IT', 92, 'Génie mécanique', 1.0),
(1612, 'Computer Science & IT', 'Computer Science & IT', 92, 'Génie mécanique', 1.0),
(1542, 'Computer Science & IT', 'Computer Science & IT', 92, 'Génie mécanique', 1.0),
(2200, 'Computer Science & IT', 'Computer Science & IT', 92, 'Génie mécanique', 1.0),
(2036, 'Computer Science & IT', 'Computer Science & IT', 97, 'Génie Pétrolier', 1.0),
(1122, 'Environmental Sciences', 'Environmental Sciences', 319, 'Génie Physique', 1.0),
(1151, 'Environmental Sciences', 'Environmental Sciences', 319, 'Génie Physique', 1.0),
(1373, 'Environmental Sciences', 'Environmental Sciences', 319, 'Génie Physique', 1.0),
(1981, 'Environmental Sciences', 'Environmental Sciences', 319, 'Génie Physique', 1.0),
(2598, 'Environmental Sciences', 'Environmental Sciences', 319, 'Génie Physique', 1.0),
(2274, 'Environmental Sciences', 'Environmental Sciences', 383, 'Ingénierie de fabrication', 1.0),
(1474, 'Environmental Sciences', 'Environmental Sciences', 391, 'Ingénierie robotique', 1.0),
(1773, 'Life Sciences', 'Life Sciences', 458, 'Ingénierie des systèmes', 1.0),
(1895, 'Life Sciences', 'Life Sciences', 458, 'Ingénierie des systèmes', 1.0),
(1855, 'Life Sciences', 'Life Sciences', 458, 'Ingénierie des systèmes', 1.0),
(1682, 'Life Sciences', 'Life Sciences', 458, 'Ingénierie des systèmes', 1.0),
(1606, 'Life Sciences', 'Life Sciences', 458, 'Ingénierie des systèmes', 1.0),
(1536, 'Life Sciences', 'Life Sciences', 458, 'Ingénierie des systèmes', 1.0),
(1114, 'Computer Science & IT', 'Computer Science & IT', 80, 'Génie biomédical', 1.0),
(1127, 'Computer Science & IT', 'Computer Science & IT', 80, 'Génie biomédical', 1.0),
(1132, 'Computer Science & IT', 'Computer Science & IT', 80, 'Génie biomédical', 1.0),
(1163, 'Computer Science & IT', 'Computer Science & IT', 80, 'Génie biomédical', 1.0),
(1176, 'Computer Science & IT', 'Computer Science & IT', 80, 'Génie biomédical', 1.0),
(1365, 'Computer Science & IT', 'Computer Science & IT', 80, 'Génie biomédical', 1.0),
(1366, 'Computer Science & IT', 'Computer Science & IT', 80, 'Génie biomédical', 1.0),
(1411, 'Computer Science & IT', 'Computer Science & IT', 80, 'Génie biomédical', 1.0),
(2566, 'Computer Science & IT', 'Computer Science & IT', 80, 'Génie biomédical', 1.0),
(1116, 'Computer Science & IT', 'Computer Science & IT', 89, 'Génie géologique', 1.0),
(1135, 'Computer Science & IT', 'Computer Science & IT', 89, 'Génie géologique', 1.0),
(1162, 'Computer Science & IT', 'Computer Science & IT', 89, 'Génie géologique', 1.0),
(1975, 'Computer Science & IT', 'Computer Science & IT', 89, 'Génie géologique', 1.0),
(1988, 'Computer Science & IT', 'Computer Science & IT', 89, 'Génie géologique', 1.0),
(2307, 'Computer Science & IT', 'Computer Science & IT', 89, 'Génie géologique', 1.0),
(2550, 'Computer Science & IT', 'Computer Science & IT', 89, 'Génie géologique', 1.0),
(2549, 'Computer Science & IT', 'Computer Science & IT', 89, 'Génie géologique', 1.0),
(2001, 'Computer Science & IT', 'Computer Science & IT', 89, 'Génie géologique', 1.0),
(1115, 'Computer Science & IT', 'Computer Science & IT', 95, 'Ingénierie navale', 1.0),
(1117, 'Computer Science & IT', 'Computer Science & IT', 95, 'Ingénierie navale', 1.0),
(1131, 'Computer Science & IT', 'Computer Science & IT', 95, 'Ingénierie navale', 1.0),
(1138, 'Computer Science & IT', 'Computer Science & IT', 95, 'Ingénierie navale', 1.0),
(1145, 'Computer Science & IT', 'Computer Science & IT', 95, 'Ingénierie navale', 1.0),
(1154, 'Computer Science & IT', 'Computer Science & IT', 95, 'Ingénierie navale', 1.0),
(1367, 'Computer Science & IT', 'Computer Science & IT', 95, 'Ingénierie navale', 1.0),
(1368, 'Computer Science & IT', 'Computer Science & IT', 95, 'Ingénierie navale', 1.0),
(1379, 'Computer Science & IT', 'Computer Science & IT', 95, 'Ingénierie navale', 1.0),
(1382, 'Computer Science & IT', 'Computer Science & IT', 95, 'Ingénierie navale', 1.0),
(1383, 'Computer Science & IT', 'Computer Science & IT', 95, 'Ingénierie navale', 1.0),
(1394, 'Computer Science & IT', 'Computer Science & IT', 95, 'Ingénierie navale', 1.0),
(1978, 'Computer Science & IT', 'Computer Science & IT', 95, 'Ingénierie navale', 1.0),
(2554, 'Computer Science & IT', 'Computer Science & IT', 95, 'Ingénierie navale', 1.0),
(2273, 'Computer Science & IT', 'Computer Science & IT', 95, 'Ingénierie navale', 1.0),
(2068, 'Computer Science & IT', 'Computer Science & IT', 95, 'Ingénierie navale', 1.0),
(2057, 'Computer Science & IT', 'Computer Science & IT', 95, 'Ingénierie navale', 1.0),
(2005, 'Computer Science & IT', 'Computer Science & IT', 95, 'Ingénierie navale', 1.0),
(1977, 'Computer Science & IT', 'Computer Science & IT', 95, 'Ingénierie navale', 1.0),
(2044, 'Computer Science & IT', 'Computer Science & IT', 95, 'Ingénierie navale', 1.0),
(2367, 'Computer Science & IT', 'Computer Science & IT', 95, 'Ingénierie navale', 1.0),
(2370, 'Computer Science & IT', 'Computer Science & IT', 95, 'Ingénierie navale', 1.0),
(2371, 'Computer Science & IT', 'Computer Science & IT', 95, 'Ingénierie navale', 1.0),
(2372, 'Computer Science & IT', 'Computer Science & IT', 95, 'Ingénierie navale', 1.0),
(2374, 'Computer Science & IT', 'Computer Science & IT', 95, 'Ingénierie navale', 1.0),
(2375, 'Computer Science & IT', 'Computer Science & IT', 95, 'Ingénierie navale', 1.0),
(2376, 'Computer Science & IT', 'Computer Science & IT', 95, 'Ingénierie navale', 1.0),
(2377, 'Computer Science & IT', 'Computer Science & IT', 95, 'Ingénierie navale', 1.0),
(2268, 'Other', 'Other', 1211, 'Conception de costumes', 1.0),
(2275, 'Other', 'Other', 1211, 'Conception de costumes', 1.0),
(2276, 'Other', 'Other', 1211, 'Conception de costumes', 1.0),
(2387, 'Arts & Design', 'Arts & Design', 47, 'Journalisme', 1.0),
(2388, 'Arts & Design', 'Arts & Design', 47, 'Journalisme', 1.0),
(2389, 'Arts & Design', 'Arts & Design', 47, 'Journalisme', 1.0),
(2387, 'Arts & Design', 'Arts & Design', 48, 'Études sur la communication de masse et les médias', 1.0),
(2388, 'Arts & Design', 'Arts & Design', 48, 'Études sur la communication de masse et les médias', 1.0),
(2389, 'Arts & Design', 'Arts & Design', 48, 'Études sur la communication de masse et les médias', 1.0),
(2390, 'Arts & Design', 'Arts & Design', 48, 'Études sur la communication de masse et les médias', 1.0),
(2396, 'Arts & Design', 'Arts & Design', 48, 'Études sur la communication de masse et les médias', 1.0),
(2397, 'Arts & Design', 'Arts & Design', 48, 'Études sur la communication de masse et les médias', 1.0),
(2387, 'Mathematics & Statistics', 'Mathematics & Statistics', 578, 'Journalisme audiovisuel', 1.0),
(2388, 'Mathematics & Statistics', 'Mathematics & Statistics', 578, 'Journalisme audiovisuel', 1.0),
(2389, 'Mathematics & Statistics', 'Mathematics & Statistics', 578, 'Journalisme audiovisuel', 1.0),
(2387, 'Mathematics & Statistics', 'Mathematics & Statistics', 580, 'Radio et Télévision', 1.0),
(2388, 'Mathematics & Statistics', 'Mathematics & Statistics', 580, 'Radio et Télévision', 1.0),
(2389, 'Mathematics & Statistics', 'Mathematics & Statistics', 580, 'Radio et Télévision', 1.0)

