export const InstitutionTypes = {
    FP: "Faculté Polydisciplinaire",
    FEG: "Faculté d'Économie et de Gestion",
    FSJES: "Faculté des Sciences Juridiques, Économiques et Sociales",
    FSA: "Faculté des Sciences Appliquées",
    FS: "Faculté des Sciences",
    FCH: "Faculté de Chariâa",
    FLASH: "Faculté des Lettres, Arts et Sciences Humaines",
    FLSH: "Faculté des Lettres et Sciences Humaines",
    ESEF: "École Supérieure d'Éducation et de Formation",
    EST: "École Supérieure de Technologie",
    ENCG: "École Nationale de Commerce et de Gestion",
    FMP: "Faculté de Médecine et de Pharmacie",
    ENSA: "École Nationale des Sciences Appliquées",
    FSB: "Faculté des Sciences de Béni Mellal",
    FSAC: "Faculté des Sciences Aïn Chock",
    FSJESM: "Faculté des Sciences Juridiques, Économiques et Sociales de Mohammedia",
    FSJESAS: "Faculté des Sciences Juridiques, Économiques et Sociales Aïn Sebaâ",
    FSJESAC: "Faculté des Sciences Juridiques, Économiques et Sociales Aïn Chock",
    FLSHM: "Faculté des Lettres et Sciences Humaines de Mohammedia",
    FLSHB: "Faculté des Lettres et Sciences Humaines de Béni Mellal",
    FLSHAC: "Faculté des Lettres et Sciences Humaines Aïn Chock",
    FMD: "Faculté de Médecine Dentaire",
    FST: "Faculté des Sciences et Techniques",
    ENSEM: "École Nationale Supérieure d'Électricité et de Mécanique",
    ENSAM: "École Nationale Supérieure d'Arts et Métiers",
    ENS: "École Normale Supérieure",
    ENSAD: "École Nationale Supérieure d'Art et de Design",
    ENSET: "École Normale Supérieure de l'Enseignement Technique",
    ENCGT: "École Nationale de Commerce et de Gestion de Tanger",
    ENSAT: "École Nationale des Sciences Appliquées de Tanger",
    ENSAH: "École Nationale des Sciences Appliquées d'Al Hoceima",
    ENSATE: "École Nationale des Sciences Appliquées de Tétouan",
    ESRFT: "École Supérieure Roi Fahd de Traduction",
    FMPT: "Faculté de Médecine et de Pharmacie de Tanger",
    FSTT: "Faculté des Sciences et Techniques de Tanger",
    FSTH: "Faculté des Sciences et Techniques d'Al Hoceima",
    FSJEST: "Faculté des Sciences Juridiques, Économiques et Sociales de Tanger",
    FSJESTE: "Faculté des Sciences Juridiques, Économiques et Sociales de Tétouan",
    FOD: "كلية أصول الدين",
    FPL: "Faculté Polydisciplinaire de Larache",
    ENIAD: "École Nationale d'Intelligence Artificielle et de Data Science",
    ENSIASD: "École Nationale Supérieure d'Intelligence Artificielle et de Science des Données",
    IFMIA: "Institut de Formation aux Métiers de l'Industrie Automobile",
    ENSCK: "École Nationale Supérieure de Chimie de Kénitra",
    ISPITS: "Institut Supérieur des Professions Infirmières et Techniques de Santé",
    I3S: "Institut Supérieur des Sciences de la Santé",
    IAV: "Institut Agronomique et Vétérinaire Hassan II",
    CHA: "Complexe Horticole d'Agadir",
    ENAM: "École Nationale d'Agriculture de Meknès",
    ENFI: "École Nationale Forestière d'Ingénieurs",
    ESITH: "École Supérieure des Industries du Textile et de l'Habillement",
    AIAC: "Académie Internationale de l'Aviation Civile",
    ENSIAS: "École Nationale Supérieure d'Informatique et d'Analyse des Systèmes",
    ESI: "École des Sciences de l'Information",
    EMI: "École Mohammadia d'Ingénieurs",
    ENSMR: "École Nationale Supérieure des Mines de Rabat",
    INPT: "Institut National des Postes et Télécommunications",
    INSEA: "Institut National de Statistique et d'Économie Appliquée",
    EHTP: "École Hassania des Travaux Publics",
    ISSF: "Institut des Sciences de Sport de Fès",
    IRFCJS: "Institut Royal de Formation des Cadres de la Jeunesse et des Sports",
    IMS: "Institut des Métiers du Sport",
    ISPM: "Institut Supérieur des Pêches Maritimes",
    ISEM: "Institut Supérieur d'Études Maritimes",
    ITPM: "Institut Technique des Pêches Maritimes",
    ISIC: "Institut Supérieur de l'Information et de la Communication",
    ISMAC: "Institut Supérieur des Métiers de l'Audiovisuel et du Cinéma",
    ISMC: "Institut Supérieur des Métiers du Cinéma",
    INBA: "Institut National des Beaux-Arts",
    ESBA: "École Supérieure des Beaux-Arts",
    INSAP: "Institut National des Sciences de l'Archéologie et du Patrimoine",
    ISADAC: "Institut Supérieur d'Art Dramatique et d'Animation Culturelle",
    AAT: "Académie des Arts Traditionnels",
    ISCAE: "Institut Supérieur de Commerce et d'Administration des Entreprises",
    ENA: "École Nationale d'Architecture",
    INAU: "Institut National d'Aménagement et d'Urbanisme",
    ISTP: "Institut Supérieur des Travaux Publics",
    EMFMBTP: "École des Métiers de Formation aux Métiers du Bâtiment et des Travaux Publics",
    CMA: "Centre des Métiers d'Art",
    ISIT: "Institut Supérieur International de Tourisme"
} 